### ISSUE TITLE
Close socket

### ISSUE THREAD

**Issue by marcguyer** [graze/dog-statsd#27]
As-is, there is no way to explicitly close the socket. On script end, of course, the socket is closed. However, for a long-running process in which a new instance of the client is created periodically, all previous instances of the object keep the socket open. As a result, eventually you run out of file descriptors and a fatal error results. 

The [StreamWriter has a destructor](https://github.com/graze/dog-statsd/blob/master/src/Stream/StreamWriter.php#L82) but this is not called when you `unset()` the `Client` object. The reason for that, I think, is that a reference to the Client still exists even if you unset your own concrete instance. Here's an example to illustrate:

```php
$statsd = new \Graze\DogStatsD\Client();
$statsd->configure(
    [
        'host' => '127.0.0.1',
        'port' => 8125,
        'namespace' => 'some.namespace',
    ]
);

$statsd->gauge('someMetric', 1);

// unset the client, freeing up it's resources
// StreamWriter::__destruct() is not called here
unset($statsd);
```

**Comment by h-bragg** [comment]
I added a `Client::deleteInstance($name)` method to remove its internal reference to that particular instance.

**Comment by marcguyer** [comment]
> It looks like when I create the StreamWriter I am passing the client, instead of the instance name. Thus creating a circular reference where it can't be destructed on destruction of the client.

You found it! I new there must be another reference to the client somewhere but didn't find it right away.
