### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by sc0rp10** [graze/dog-statsd#40]
Hi, thank you for this great library that we actively using in our projects - it is very useful for us.

As the other modern PHP world in past days, we updating our software to use new shine PHP8 features, but some libraries blocked updating process because of using strict `platform.php` constraint in their `composer.json`-s, and this library has the same problem.

Could you please update metadata to allow PHP8? I can make PR with that changes, but I need your help - merge & tag new version in packagist. 
Thanks!

**Comment by michondr** [comment]
same for us. time is ticking!

some progress would be appreciated :)

**Comment by biggianteye** [comment]
This has now been done. Let me know if there are any problems.
